apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app : harbor
  name: harbor
spec:
  host: harbor-harbor.apps.okd4.ktdemo.duckdns.org
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: my-harbor-portal
    weight: 100
  wildcardPolicy: None
